networks:
    etl-net:
        driver: bridge

services:
    hadoop:
        image: silicoflare/hadoop:amd
        container_name: hadoop
        ports:
            - "9870:9870"
            - "8088:8088"
            - "9864:9864"
            - "8080:8080"
            - "4040:4040"
        tty: true
        stdin_open: true
        networks:
            - etl-net

    broker:
        image: apache/kafka:latest
        container_name: broker
        ports:
            - "9094:9094"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://broker:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://broker:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,EXTERNAL://localhost:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_NUM_PARTITIONS: 3
        networks:
            - etl-net
